### ISSUE TITLE
basic money change

### ISSUE THREAD

**Issue by KRTSZ** [wehelpvip/wehelp.vip#1]
A database and three input and output forms.

user form 1 initializes a dataset of the database with initial input.
user form 2 shows the user work in progress of a dataset and allows to input additional data for milestones that have been achieved.
administrator form 3 contains all information of the database, including input not shown in user form 1 and 2.

output user form 1:
-description of the process
-date and time of initialization

input user form 1;
(optional) string: user name (Cyrillic alphabet)
string: bank account holder name (Latin alphabet)
string: IBAN of bank account
string: description of the problem
integer: to be changed amount in € (upper limit 300)
string: mobile phone number
string: unique identifier
(optional) string: email address

use case user form 1:
The user receives form 1 with description of the required input in the distinct fields to initialize a dataset of a money change process in the database. Fills in all data, except the unique identification number. The unique identifier is sent to the mobile phone number per SMS. After receiving it, the user puts the unique identifier into the user form 1 to finish the registration process. The input data is then stored with date and time of initialization as a new dataset in the database.

output user form 2:
-input data from user form 1
-work in progress status
-description for milestone feedback
-date and time of initialization
-content of emails to users depending on work in progress status

input user form 2:
(optional) pdf/jpeg file: account confirmation on money received
pdf/jpeg file: donation receipt

use case user form 2:
User enters unique identifier to unlock user form 2 of a dataset from the database. It shows data from user form 1 and the work in progress status set by the administration. It has two input fields for milestones achieved.

output administrator form 3:
-database with all datasets in overview function showing all stored information
-ability to select description of the problem in a dataset for selective complete view with additional output of user name and unique identifier

input administrator form 3:
value: priority
value: work in progress status
boolean: fraud suspicion (default false)
boolean: donation received in €
boolean: donation sent to Ukraine

use case administrator form 3:
The administrator receives new datasets in the database overview. Reads the description of the problem and assigns a priority value. This moves the work in progress status to a new value. If the priority is low, a description of the nearest possibility to change money is sent. This is a standardized email describing how to travel to Austria and where to change money in Salzburg or Innsbruck near the train station. After the email is sent, work in progress status automatically takes a new value.
If the priority is high, the user case is put in the top of the database for a donation, secondary ordered by date of  initialization. If € money is sent to the bank account an email is also sent with known institutions for donations to Ukraine. Work in progress status is updated. Upon feedback on achieved milestones of receiving the money and donating to Ukraine, work in progress status is twice updated and the use case closed.

**Comment by razbakov** [comment]
This issue is too big. Should be splitted.
